-- daves_castbar / FrostCuts.lua
-- GENERATED by tools/Make-CastbarMedia.ps1 - do not edit. The frost cut lines baked into
-- Media/frost_cutN_*.tga, as { {x, y}, ... } per cut in texture pixels (512 x 64, y down),
-- from the first corner at or after x = 0 to that corner + 512.

local _, ns = ...
ns.FROST_CUTS = {{{0,0},{256,64},{512,0}},{{64,64},{192,0},{320,64},{448,0},{576,64}},{{68.27,64},{153.6,0},{238.93,64},{324.27,0},{409.6,64},{494.93,0},{580.27,64}},{{66.56,0},{322.56,64},{578.56,0}},{{102.4,36.48},{230.4,27.52},{358.4,36.48},{486.4,27.52},{614.4,36.48}}}
